elasticsearch:
  image: portefaix/elasticsearch:1.7.1
  name: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"

kibana:
  build: "4.1"
  name: kibana
  ports:
    - "5601:5601"
  links:
  - elasticsearch
